export const TRAINEE_SIGNUP_INITIAL_VALUES = {
  smm: "",
  bfm: "",
  tbw: "",
  goal: "",
  email: "",
  gender: "",
  weight: "",
  height: "",
  protein: "",
  password: "",
  last_name: "",
  first_name: "",
  body_images: [],
  role: "Trainee",
  phone_number: "",
  training_goal: "",
  profile_pic: null,
  date_of_birth: "",
  activity_level: "",
  food_sensitive: "",
  injury_details: "",
  confirm_password: "",
};

export const CHANGE_PASSWORD_INITIAL_VALUES = {
  new_password: "",
  confirm_password: "",
  previous_password: "",
};
