name: Build React App

on:
  push:
    branches:
      - staging # Replace with your branch name
  pull_request:

jobs:
  build:
    name: Build React.js Application
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set environment variables
        run: |
          echo "REACT_APP_FIREBASE_API_KEY='AIzaSyAhkd3kt91KiPEkWKFXfiNlTLMbtMQ6QDY'" >> .env
          echo "REACT_APP_FIREBASE_AUTH_DOMAIN='fitnee-599e6.firebaseapp.com'" >> .env
          echo "REACT_APP_FIREBASE_PROJECT_ID='fitnee-599e6'" >> .env
          echo "REACT_APP_FIREBASE_STORAGE_BUCKET='fitnee-599e6.appspot.com'" >> .env
          echo "REACT_APP_FIREBASE_SENDER_ID='656320859335'" >> .env
          echo "REACT_APP_FIREBASE_APP_ID='1:656320859335:web:90ecc985a07ec6ae5302e2'" >> .env
          echo "REACT_APP_FIREBASE_MEASUREMENT_ID='VY7M0GFXTL'" >> .env
          echo "REACT_APP_BACKEND_BASE_URL='https://staging.fitnee.fit'" >> .env
          echo "REACT_APP_HYPERPAY_REDIRECT_URL='/trainee/dashboard'" >> .env
      - name: echo
        run: cat .env

      - name: Write private key to cert.pem
        run: |
          cat <<EOF > cert.pem
          -----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
          QyNTUxOQAAACCCQv3jZcvYeoIZ+NgPQiVTaIJ8dx6o/Ofn9SYVZreL+QAAAJgWqZAxFqmQ
          MQAAAAtzc2gtZWQyNTUxOQAAACCCQv3jZcvYeoIZ+NgPQiVTaIJ8dx6o/Ofn9SYVZreL+Q
          AAAEDOLIQ3o3kW4Bp1FAWFheiNrj2NS4mJbGiD6Qya0t7Ai4JC/eNly9h6ghn42A9CJVNo
          gnx3Hqj85+f1JhVmt4v5AAAAD2FobWVkc2hAYWhtZWRzaAECAwQFBg==
          -----END OPENSSH PRIVATE KEY-----
          EOF
      
      - name: change perm
        run:  chmod 600 cert.pem

      - name: read the key
        run: cat cert.pem 


      - name: Execute Remote Script
        run: |
          ssh -i cert.pem -o StrictHostKeyChecking=no ubuntu@16.170.125.0 sh /home/ubuntu/fe-deploy.sh
      

    env:
      REACT_APP_FIREBASE_API_KEY: 'AIzaSyAhkd3kt91KiPEkWKFXfiNlTLMbtMQ6QDY'
      REACT_APP_FIREBASE_AUTH_DOMAIN: 'fitnee-599e6.firebaseapp.com'
      REACT_APP_FIREBASE_PROJECT_ID: 'fitnee-599e6'
      REACT_APP_FIREBASE_STORAGE_BUCKET: 'fitnee-599e6.appspot.com'
      REACT_APP_FIREBASE_SENDER_ID: '656320859335'
      REACT_APP_FIREBASE_APP_ID: '1:656320859335:web:90ecc985a07ec6ae5302e2'
      REACT_APP_FIREBASE_MEASUREMENT_ID: 'VY7M0GFXTL'
      REACT_APP_BACKEND_BASE_URL: 'https://staging.fitnee.fit'
      REACT_APP_HYPERPAY_REDIRECT_URL:  '/trainee/dashboard'