name: Build React App

on:
  push:
    branches:
      - production # Replace with your branch name
  pull_request:

jobs:
  build:
    name: Build React.js Application
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
      

      - name: Write private key to cert.pem
        run: |
          cat <<EOF > cert.pem
          -----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
          QyNTUxOQAAACDnP09ot1b4jhZ0NBVPkljY+vqmDxfeGo9c/3GZxpxeigAAAJjr8ap+6/Gq
          fgAAAAtzc2gtZWQyNTUxOQAAACDnP09ot1b4jhZ0NBVPkljY+vqmDxfeGo9c/3GZxpxeig
          AAAEDXkWWcopLATfBiITpR5pxuhTDAaw9YLb5gFQWd6jMiruc/T2i3VviOFnQ0FU+SWNj6
          +qYPF94aj1z/cZnGnF6KAAAAD2FobWVkc2hAYWhtZWRzaAECAwQFBg==
          -----END OPENSSH PRIVATE KEY-----
          EOF
      
      - name: change perm
        run:  chmod 600 cert.pem

      - name: read the key
        run: cat cert.pem 


      - name: Execute Remote Script
        run: |
          ssh -i cert.pem -o StrictHostKeyChecking=no ubuntu@16.170.125.0 sh /home/ubuntu/fe-deploy.sh
      
